spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: alumnos-user
          uri: http://localhost:8090
          predicates:
            - Path=/api/user/**

        - id: alumnos-admin
          uri: http://localhost:8090
          predicates:
            - Path=/api/admin/**

        - id: alumnos-media
          uri: http://localhost:8090
          predicates:
            - Path=/media/**

        - id: alumnos-profe
          uri: http://localhost:8090
          predicates:
            - Path=/api/profe/**

        - id: auth
          uri: http://localhost:9090
          predicates:
            - Path=/api/auth/**
